GET http://localhost:3001/product

###

GET http://localhost:3001/brand

###

GET http://localhost:3001/category

###

POST http://localhost:3001/product
Content-Type: application/json

{
  "name": "Notebook Dell Inspiron",
  "photo": "https://exemplo.com/notebook.jpg",
  "description": "Notebook Dell Inspiron 15, Intel i7, 16GB RAM, 512GB SSD",
  "price": 4500.00,
  "categoryId": 1,
  "brandId": 1
}

###

POST http://localhost:3001/brand
Content-Type: application/json

{
  "name": "Dell"
}

###

POST http://localhost:3001/category
Content-Type: application/json

{
  "name": "Notebook"
}

###

POST http://localhost:3001/user
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "yourpassword"
}